apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: mydeployment
    kind: frontend
spec:
  template:
    metadata:
      name: nginx-deploy
      labels:
        app: nginxdeploy
        type: frontend
    spec:
      containers:
        - name: nginx
          image : nginx:alpine
  replicas: 3
  selector:
    matchLabels:
      type: frontend