apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  container:
    - name: nginx
      image: nginx:alpine
    - name: redis
      image: redis
    - name: memcached
      image: memcached           