apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: mydeployment
    kind: frontend
spec:
  template:
    metadata:
      name: my-first-pod
      labels:
        app: myFirstPod
        type: frontend
    spec:
      containers:
        - command:
            - sleep
            - "3600"
          image: busybox
          name: pods-simple-container
  replicas: 5
  selector:
    matchLabels:
      type: frontend