apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: busyboxdeploy
    kind: frontend
spec:
  template:
    metadata:
      name: busybox-deploy
      labels:
        app:  busyboxdeploy
        type: frontend
    spec:
      containers:
        - command:
            - sleep
            - "3600"      
        - name: busybox
          image : busybox
  replicas: 3
  selector:
    matchLabels:
      type: frontend