apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    metadata:
      name: busybox-deploy
    spec:
      containers:
        - command:
            - sleep
            - "3600"      
        - name: busybox
          image : busybox
  replicas: 3
