apiVersion: v1 
kind: Pod 
metadata: 
  name: healthy-pod 
spec: 
  containers: 
  - name: healthy-pod 
    image: nginx 
    ports: 
        - containerPort: 80 
    livenessProbe: 
      exec:
        command:
        - cat
        - /usr/share/nginx/html/index.html
      initialDelaySeconds: 2
      periodSeconds: 5 
      timeoutSeconds: 1
      successThreshold: 3
      failureThreshold: 5
    readinessProbe:
       initialDelaySeconds: 5
       periodSeconds: 1
       timeoutSeconds: 3
       successThreshold: 7
       failureThreshold: 1  