apiVersion: v1 
kind: Pod 
metadata: 
  name: healthy-pod 
spec: 
  containers: 
  - name: healthy-pod 
    image: nginx 
    ports: 
        - containerPort: 80 
    livenessProbe: 
      exec:
        command:
        - cat
        - /usr/share/nginx/html/index.html
      initialDelaySeconds: 2
      periodSeconds: 5 
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 5
    readinessProbe:
      initialDelaySeconds: 
      periodSeconds: 5
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 1
      exec:
        command:
        - cat
        - /etc/nginx/nginx.conf